### ISSUE TITLE
Broken in WP 4.9.x

### ISSUE THREAD

**Issue by ginsterbusch** [DevinWalker/wp-rollback#78]
# Bug Report

## User Story

Tested it on ClassicPress 1.7.x, which is an active fork of WP 4.9.x (with a few security backports from WP 5) and ClassicPress v2-nightly (which is a refork based on WP 6.2 without Gutenberg, everything else is the same). 
Expected it to work flawlessly, but is broken when trying to rollback a plugin or theme.

## Current Behavior
When clicking on the 'rollback' for any plugin, you get redirected to the updates screen, but aside of the usual Admin Navigation, the page is empty. Query monitor lights up with missing script and style errors instantly.

## Expected Behavior
A working solution, despite not being able to load scripts and styles not existing in WP 4.9.x.

## Bug Type
- [x] This bug describes functionality that once worked as expected in version 1.7.3.

## Steps to Reproduce

1. Install WP 4.9.x OR ClassicPress 1.7.x
2. Install plugin, and some others for testing purposes, eg. Instant Images in its current version, which doesnt work, because it requires react and all the other gutenborg components, but works in WP 4.9.x / CP 1.7.x with version 4.2.0
3. Try to rollback Instant Images from 6.x to 4.2.0

## Possible Solution
Downgrade to 1.7.3.

## Acceptance Criteria

- [ ] e.g. Something happens when an action is taken.
- [ ] e.g. Something does not happen when an action is taken.
- [ ] e.g. Fixing behavior in Component A does not affect existing behavior in Component B.

## Environment

Server: some Linux or Unix
Client: all browsers (its a server-side issue)
WP: 4.9
CP: 1.7.x, v2-rc1 / nightly (latest)

**Comment by DevinWalker** [comment]
Hey @ginsterbusch, the 2.0+ versions of WP Rollback won't work with 4.8.x or ClassicPress because I'm using the WordPress components in the new React-built interface. A potential workaround is to use the 1.7.x versions.

My apologies; I just realized as well that the minimum WordPress requirement in 2.0+ was still set to WP 4.8, and this is misleading. I updated it in this commit: 74945b514187394c4d12f4ffec100538a2ef169b 

You can find past releases here: https://github.com/DevinWalker/wp-rollback/releases 

Thanks for your interest

**Comment by ginsterbusch** [comment]
Ok, then I just gonna fork it and create a ClassicPress-compatible version. In theory, it should also work with WP 4.9.x, but that is not my main focus.
